from .recommendation01 import Recommendation01
from .recommendation06 import Recommendation06
from .recommendation07 import Recommendation07
from .recommendation08 import Recommendation08
from .recommendation20 import Recommendation20
from .recommendation09 import recommendation09
from .recommendation16 import recommendation16
from .recommendation23 import recommendation23
from .recommendation33 import recommendation33
from .recommendation38 import recommendation38
