from .recommendation00 import Recommendation00
from .recommendation01 import Recommendation01
from .recommendation03 import Recommendation03
from .recommendation06 import Recommendation06
from .recommendation07 import Recommendation07
from .recommendation08 import Recommendation08
from .recommendation09 import Recommendation09
from .recommendation16 import Recommendation16
from .recommendation17 import Recommendation17
from .recommendation19 import Recommendation19
from .recommendation20 import Recommendation20
from .recommendation23 import Recommendation23
from .recommendation26 import Recommendation26
from .recommendation31 import Recommendation31
from .recommendation33 import Recommendation33
from .recommendation34 import Recommendation34
from .recommendation36 import Recommendation36
from .recommendation38 import Recommendation38
from .recommendation44 import Recommendation44
